/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

/**
 *
 * @author alexd
 */

public class VentanaEventos extends javax.swing.JFrame {
private modelo.Usuario usuario;
    /**
     * Creates new form VentanaEventos
     */
    public VentanaEventos(modelo.Usuario usuario) {
        initComponents();
        cargarEventos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEventos = new javax.swing.JTable();
        btnRegistrar = new javax.swing.JButton();
        btnCancelarEvento = new javax.swing.JButton();
        btnCerarr = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Eventos Disponibles");

        tablaEventos.setBackground(new java.awt.Color(202, 213, 40));
        tablaEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"UTSmart",  new Boolean(true),  new Double(100.0)},
                {"CIINATIC",  new Boolean(true),  new Double(150.0)},
                {"Grados UTS	", null,  new Double(0.0)},
                {"Expobienestar	",  new Boolean(true),  new Double(75.0)}
            },
            new String [] {
                "Nombre", "Otorga Duts?", "Duts Otorgados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Boolean.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaEventos.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tablaEventos);
        tablaEventos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnRegistrar.setBackground(new java.awt.Color(202, 213, 40));
        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnRegistrar.setText("Inscribirse");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnCancelarEvento.setBackground(new java.awt.Color(202, 213, 40));
        btnCancelarEvento.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCancelarEvento.setText("Cancelar Inscripcion");
        btnCancelarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEventoActionPerformed(evt);
            }
        });

        btnCerarr.setBackground(new java.awt.Color(202, 213, 40));
        btnCerarr.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnCerarr.setText("Cerrar");
        btnCerarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerarrActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/logo_uts_90x70.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelarEvento)
                        .addGap(30, 267, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCerarr)
                    .addComponent(jLabel5)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEvento)
                    .addComponent(btnCerarr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       int filaSeleccionada = tablaEventos.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, "Por favor selecciona un evento.");
        return;
    }

    // Verificamos si otorga DUTS
    String otorgaDuts = tablaEventos.getValueAt(filaSeleccionada, 1).toString();
    if (!otorgaDuts.equals("Sí")) {
        JOptionPane.showMessageDialog(this, "Este evento no otorga DUTS.");
        return;
    }

    // Obtener los DUTS otorgados
    double dutsEvento = Double.parseDouble(tablaEventos.getValueAt(filaSeleccionada, 2).toString());

    // Sumar los DUTS al usuario
    usuario.agregarDUTS(dutsEvento);

    JOptionPane.showMessageDialog(this, "Te has inscrito correctamente.\nDUTS actuales: " + usuario.getDuts());// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnCancelarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEventoActionPerformed
        JOptionPane.showMessageDialog(this, "Has cancelado tu inscripción.");// TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarEventoActionPerformed

    private void btnCerarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerarrActionPerformed
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnCerarrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                modelo.Usuario usuario = new modelo.Usuario("", "", "");
                new VentanaEventos(usuario).setVisible(true);
            }
        });
    }
private void cargarEventos() {
    String[] columnas = {"Nombre", "¿Otorga DUTS?", "DUTS Otorgados"};
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    // Supongamos que tienes una lista de eventos (aquí un ejemplo simulado):
    List<modelo.Evento> eventos = new ArrayList<>();
    eventos.add(new modelo.Evento("UTSmart", true, 100));
    eventos.add(new modelo.Evento("CIINATIC", true, 150));
    eventos.add(new modelo.Evento("Grados UTS", false, 0));
    eventos.add(new modelo.Evento("Expobienestar", true, 75));

    for (modelo.Evento e : eventos) {
        Object[] fila = {
            e.getNombre(),
            e.otorgaDuts() ? "Sí" : "No",
            e.getDutsOtorgados()
        };
        modelo.addRow(fila);
    }
    

    tablaEventos.setModel(modelo);
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEvento;
    private javax.swing.JButton btnCerarr;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaEventos;
    // End of variables declaration//GEN-END:variables
}
